const CELL_HEIGHT = 22;
const CELL_WIDTH = 94;
const CELL_WIDTH_LEFT_TITLE = 60;
const CELL_WIDTH_LEFT_GROUP = 22;
const CELL_TYPE_DEFAULT = 'string';

export {
  CELL_HEIGHT,
  CELL_WIDTH,
  CELL_WIDTH_LEFT_TITLE,
  CELL_WIDTH_LEFT_GROUP,
  CELL_TYPE_DEFAULT,
};
