const CELL_WIDTH_TITLE = 60;
const CELL_WIDTH_GROUP = 20;
const CELL_HEIGHT_TITLE = 22;
const CELL_HEIGHT_GROUP = 20;
const CELL_HEIGHT_BODY = 22;
const CELL_WIDTH_BODY = 94;

// const CELL_WIDTH_LEFT_TITLE = 60;

// const CELL_HEIGHT = 22;

// const CELL_WIDTH = 94;

// const CELL_WIDTH_LEFT_GROUP = 20;
const CELL_TYPE_DEFAULT = 'string';

export {
  CELL_WIDTH_TITLE,
  CELL_WIDTH_GROUP,
  CELL_HEIGHT_TITLE,
  CELL_HEIGHT_GROUP,
  CELL_HEIGHT_BODY,
  CELL_WIDTH_BODY,

  // CELL_HEIGHT,
  // CELL_WIDTH,
  // CELL_WIDTH_LEFT_TITLE,
  // CELL_WIDTH_LEFT_GROUP,
  CELL_TYPE_DEFAULT,
};
