  --actionCell(cellName) // used at page
  | addArea(cellName, areaName, shiftType = SHIFT_TYPE.VERTICAL) // надо удалить используется только в скрипте для добавления строки
  | calculateCellValue(cellName)
  | deleteArea(range, shiftType = null)
  | deleteRange(range, deleteMode = null)
  | deserialize(data)
  | deserializeArea(sectionKey, sectionDataItem)
  | editingCell(cellName, cellValue)
  -- executeAction(cellName) // used in actionCell()
    fillArea(data, parameters) // заполнить параметры в области setParametersArea()
    getAreaCopy()
    getAreaForRange(range)
    getAreaHeight()
    getAreaValue(parameters) // used in serializationDataSection()
    getAreaWidth()
    getCell(cellName)
    getCellFormula(cellName)
    getCellScripts(cellName)
    getCellValue(cellName)
    getCellParameter(cellName, cellParameter) // разбить на получение каждого атрибута
    getCellStyles(cellName)
    getCellType(cellName)
    getCellKeysInLevel(range, level, rangeType = RANGE_TYPE.ROW)
    getCellsInRange(range, returnFormat = RETURN_FORMAT.ENTRIES)
    getColumn(columnName)
    getColumnKeysInRange(range)
    getColumnType(columnName)
    getDocument(JSONFormat = false)
    getFormularsCellsSet()
    getLastColumn()
    getLastColumnInRow(numberRow)
    getLastRow()
    getListNamedAreasForRange(range)
    getNamedArea(areaName)
    getNamedAreas()
    getRangeByAreaName(areaName)
    getRangeByCellName(cellName, areaName = null, rangeType = RANGE_TYPE.ROW) // ??????
    getRangeToEdge(rangeFrom)
    getRow(rowName)
    getRowType(rowName)
    getRowKeysInRange(range)
    getSectionSettings(sectionName)
    getScripts(scriptName)
    getStyles()
    hasEditing(cellName)
    hasEditingCell(cellName)
    hasEditingSheet(cellName)
    hasNamedArea(namedArea)
    insertArea(numberColumn, numberRow, area, shiftType = null)
    joinArea(area)
    putArea(area)
    recalculateFormulas()
    serializationDataSection(nameDataSection, settings)
    setCell(cellName, cellValue)
    setCellValue(cellName, cellValue, cellParameter = '', isErrorStop = false)
    setColumn(columnName, columnValue)
    setColumnGroup(level, columnName)
    setRow(rowName, rowValue)
    setRowGroup(level, rowName)
    setTableDocumentTemplate(template)
    setTableDocumentSettings(settings)
    updateNamedArea(namedAreasArea, numberRow, numberColumn)
    updateStyles(stylesArea)
    validateCellValue(cellName, cellValue, cellParameter)
