export default {
  countColumn: 50,
  countRow: 1000,
  columnCount: 50,
  rowCount: 1000,
  sheetSpace: {
    column: 50,
    row: 1000,
  },
  columnsJSON: `{
    "a":{"width":10,"fixed":"true"},
    "b":{"width":10,"fixed":"true"},
    "c":{"width":10,"fixed":"true"},
    "d":{"width":120},
    "e":{"width":80},
    "f":{"width":100},
    "g":{"width":100},
    "h":{"width":50},
    "i":{"width":50},
    "j":{"width":50},
    "m":{"width":80},
    "n":{"columnGroup":"6"},
    "o":{"parent":"n","width":50},
    "p":{"columnGroup":"4","parent":"n"},
    "q":{"parent":"p"},
    "r":{"parent":"p"},
    "s":{"parent":"p"},
    "t":{"width":20}
  }`,
  //  Variant 3
  rowsJSON: `{
    "1":{"fixed":"true"},
    "2":{"height":40},
    "5":{"height":30},
    "6":{"height":30},
    "7":{"height":30,"type":"number"},
    "8":{"height":30,"type":"number"},
    "9":{"height":46,"type":"number"},
    "10":{"height":36},
    "11":{"type":"number"},
    "14": {"rowGroup": "13"},
    "15": {"parent": "14"},
    "16": {"rowGroup": "7","parent": "14"},
    "17": {"rowGroup":"4","parent": "16"},
    "18": {"parent": "17"},
    "19": {"parent": "17"},
    "20": {"parent": "17"},
    "21": {"parent": "16"},
    "22": {"parent": "16"},
    "23": {"parent": "14"},
    "24": {"rowGroup":"2","parent": "14"},
    "25": {"parent": "24"},
    "26": {"parent": "14"},
    "27": {"rowGroup": "8"},
    "28": {"parent": "27"},
    "29": {"parent": "27"},
    "30": {"rowGroup":"3","parent": "27"},
    "31": {"parent": "30"},
    "32": {"parent": "30"},
    "33": {"parent": "27"},
    "34": {"parent": "27"}
  }`,

  cellsJSON: `{
    "d2":{"style":"fn1_3 fn4","value":"Квитанция"},

    "d3":{"style":"br1 br3 fn1","value":"Плательщик:"},
    "e3":{"style":"br1 fn1_2 fn4 fn5","value":"Иванов Иван Иванович","colspan":3},
    "h3":{"style":"br1 fn1","value":"адрес:"},
    "i3":{"style":"br1 fn1_2 fn4","value":"Ленина, 33, кв. 33","colspan":3},
    "l3":{"style":"br1 fn1","value":"проживает, чел.:"},
    "m3":{"style":"br1 br4 fn1_2 fn4","value":"1","type":"number"},

    "d4":{"style":"br2 br3 fn1","value":"л/с №:"},
    "e4":{"style":"br2 fn1_2 fn4 fn5","value":"33333"},
    "f4":{"style":"br2 fn1","value":"оборудование:"},
    "g4":{"style":"br2 fn1 fn4","value":"плита газоэл.(2газ.эл.розжиг)","colspan":5},
    "i4":{"style":"br2 fn1_2 fn4","value":"Ленина, 33, кв. 33","colspan":3},
    "l4":{"style":"br2 fn1","value":"площадь, кв. м:"},
    "m4":{"style":"br2 br4 fn1_2 fn4","value":"31.6","type":"number"},

    "d5":{"style":"br3 br4 fn0","value":"Счет за "},
    "e5":{"style":"br0 fn0","value":"Остаток на начало месяца*","rowspan":2},
    "f5":{"style":"br0 fn0","value":"Оплата и перерасчеты в расчетном месяце","rowspan":2},
    "g5":{"style":"br0 fn0","value":"Тариф","rowspan":2},
    "h5":{"style":"br0 fn0","value":"Показания","colspan":2},
    "j5":{"style":"br0 fn0","value":"Начислено за месяц","colspan":2},
    "l5":{"style":"br0 fn0","value":"Итого к оплате","rowspan":2},
    "m5":{"style":"br0 fn0","value":"Оплачено","rowspan":2},

    "d6":{"style":"br0 br3 fn1_2 fn2 fn4","value":"2021-05-12","type":"date"},
    "h6":{"style":"br0 fn0","value":"пред."},
    "i6":{"style":"br0 fn0","value":"тек."},
    "j6":{"style":"br0 fn0","value":"куб. м."},
    "k6":{"style":"br0 fn0","value":"руб."},

    "d7":{"style":"br0 br3 fn1 fn3","value":"Газоснабжение","type":"string"},
    "e7":{"style":"br0 fn0 fn4","value":"276.00"},
    "f7":{"style":"br0 fn0 fn4","value":"276.00"},
    "g7":{"style":"br0 fn1 fn2","value":"138 руб. за куб. м.","type":"string"},
    "h7":{"style":"br0 fn0 fn4","value":"35"},
    "i7":{"style":"br0 fn0 fn4","value":"36"},
    "j7":{"style":"br0 fn0 fn4","value":"1"},
    "k7":{"style":"br0 fn0 fn4","value":"138.00"},
    "l7":{"style":"br0 fn0 fn4","value":"138.00"},
    "m7":{"style":"br0 fn0 fn4","value":""},

    "d8":{"style":"br0 br3 fn1 fn3","value":"Техническое обслуживание плиты","type":"string"},
    "e8":{"style":"br0 fn0 fn4","value":"0.00"},
    "f8":{"style":"br0 fn0 fn4","value":"0.00"},
    "g8":{"style":"br0 fn1 fn2","value":"376 руб. в год","type":"string"},
    "h8":{"style":"br0 fn0 fn4","value":"Х","colspan":3,"type":"string"},
    "k8":{"style":"br0 fn0 fn4","value":"0.00"},
    "l8":{"style":"br0 fn0 fn4","value":"0.00"},
    "m8":{"style":"br0 fn0 fn4","value":""},

    "d9":{"style":"br0 br3 fn1 fn3","value":"Техническое обслуживание общедомовых сетей","type":"string"},
    "e9":{"style":"br0 fn0 fn4","value":"-10.74"},
    "f9":{"style":"br0 fn0 fn4","value":"0.00"},
    "g9":{"style":"br0 fn1 fn2 fn3","value":"0.5 руб. за кв.м. в мес.","type":"string"},
    "h9":{"style":"br0 fn0 fn4","value":"Х","colspan":3,"type":"string"},
    "k9":{"style":"br0 fn0 fn4","value":"15.80"},
    "l9":{"style":"br0 fn0 fn4","value":"5.06"},
    "m9":{"style":"br0 fn0 fn4","value":""},
    
    "d10":{"style":"br2 br3 fn1 fn3","value":"Контрольные показания на 31.07.2019:","colspan":2},
    "f10":{"style":"br0 fn4","value":"19"},
    "g10":{"style":"br2 fn1 fn4","value":"Текущие показания прибора учета:","colspan":3},
    "j10":{"style":"br0 fn4","value":"37"},
    "k10":{"style":"br0 fn0 fn4","value":"Всего к оплате:"},
    "l10":{"style":"br0 fn2 fn4","value":"143.06"},
    "m10":{"style":"br0 fn0 fn4","value":""},

    "d11":{"style":"br0 br3 fn1 fn4","value":"Пеня","type":"string"},
    "e11":{"style":"br0 fn1 fn2","value":"0.00"},
    "f11":{"style":"br0 fn1 fn2","value":"0.00"},
    "g11":{"style":"br0 fn1 fn2 fn3","value":"X","colspan":4,"type":"string"},
    "k11":{"style":"br0 fn1 fn2 fn4","value":"0.00"},
    "l11":{"style":"br0 fn1 fn2 fn4","value":"0.00"},
    "m11":{"style":"br0 fn1 fn2","value":""}

  }`,

  styles: [
    { name: 'br0', list: { borderBottom: '2px solid black', borderRight: '2px solid black' } },
    { name: 'br1', list: { borderTop: '2px solid black' } },
    { name: 'br2', list: { borderBottom: '2px solid black' } },
    { name: 'br3', list: { borderLeft: '2px solid black' } },
    { name: 'br4', list: { borderRight: '2px solid black' } },

    { name: 'fn0', list: { fontSize: '0.8em', justifyContent: 'center', whiteSpace: 'unset' } },
    { name: 'fn1', list: { fontSize: '0.8em' } },
    { name: 'fn1_2', list: { fontSize: '0.9em' } },
    { name: 'fn1_3', list: { fontSize: '1.1em' } },
    { name: 'fn2', list: { justifyContent: 'center' } },
    { name: 'fn3', list: { whiteSpace: 'unset' } },
    { name: 'fn4', list: { fontWeight: 'bold' } },
    { name: 'fn5', list: { textTransform: 'uppercase' } },
  ],
};
